### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Zhao-github** [ElemeFE/element-dashboard#12]
当我运行build的时候出现如下图所示的提示性报错，导致我没有找到build出的文件在哪里.....
![image](https://cloud.githubusercontent.com/assets/12930222/22860747/421cec7a-f142-11e6-9244-3095e5ff6c0f.png)

**Comment by xhblovewmy** [comment]
@Zhao-github 这个报错对build是没有影响的，从截图来看，项目已经build成功了，build出的文件在docs文件夹里。这个报错是因为执行了一条冗余的代码，现已删除，你可以拉一下最新的代码。

**Comment by Zhao-github** [comment]
@vvliebe 已经下载尝试，build成功，并且没有再报错了，但是直接预览`index.html`还是没有内容，原因出在JS和CSS的路径上。
当前生成：`<script type=text/javascript src=/element-dashboard/static/js/app.ffbfab87685e26c9bf3d.js></script>`
期望生成：`<script type=text/javascript src=./static/js/app.ffbfab87685e26c9bf3d.js></script>`

**Comment by xhblovewmy** [comment]
@Zhao-github 看一下你发的截图里的Tip，已经有说明，需要起一个server
![image](https://cloud.githubusercontent.com/assets/10060635/23057633/ffcf5d74-f52b-11e6-9b1f-dc5114209c6d.png)

**Comment by Zhao-github** [comment]
Thanks
